"""add resource2

Revision ID: bd1c961e3b8a
Revises: 
Create Date: 2024-12-01 21:36:50.411736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.types import Text


# revision identifiers, used by Alembic.
revision: str = 'bd1c961e3b8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attr1', sa.String(), nullable=False),
    sa.Column('attr2', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource2')
    # ### end Alembic commands ###